apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: consumer-binding
  namespace: distributed-rabbit
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  source: federation.in
  destination: consumer.queue
  destinationType: queue
  routingKey: ""
  rabbitmqClusterReference:
    name: rabbit2
