---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: federation-out-rabbit1
  namespace: distributed-rabbit
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: federation.out
  type: direct
  durable: true
  rabbitmqClusterReference:
    name: rabbit1
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: federation-out-rabbit2
  namespace: distributed-rabbit
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: federation.out
  type: direct
  durable: true
  rabbitmqClusterReference:
    name: rabbit2
