apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: federation-policy
  namespace: distributed-rabbit
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: federation-policy
  pattern: "^federation\\.in$"
  applyTo: exchanges
  definition:
    federation-upstream: rabbit1-upstream
  rabbitmqClusterReference:
    name: rabbit2
