apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-rabbit1.yaml
  - cluster-rabbit2.yaml
  - exchange-federation-in.yaml
  - queue-consumer.yaml
  - binding-consumer.yaml
  - federation-upstream.yaml
  - federation-policy.yaml
  - rabbitmq-secret.yaml
