apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: consumer-queue
  namespace: distributed-rabbit
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: consumer.queue
  durable: true
  rabbitmqClusterReference:
    name: rabbit2
