apiVersion: v1
kind: Secret
metadata:
  name: rabbit1-amqp-uri
  namespace: distributed-rabbit
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  uri: "amqp://guest:guest@rabbit1:5672/%2f"
