framework:
    messenger:
        transports:
            consumer:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: federation.in
                        type: direct
                    queues:
                        consumer.queue:
                            binding_keys:
                                - ''

            response:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: federation.out
                        type: direct

        routing:
            App\Message\FederationMessage: consumer
            App\Message\ConfirmationMessage: response
