apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distributed-rabbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/grobacz/distributed-rabbit.git
    targetRevision: master
    path: k8s/overlays/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: distributed-rabbit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
