apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-enabled-plugins
  namespace: distributed-rabbit
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_federation,rabbitmq_federation_management].
