apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: distributed-rabbit
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: producer:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          envFrom:
            - configMapRef:
                name: producer-config
          volumeMounts:
            - name: log-volume
              mountPath: /app/var/log
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

        - name: confirmation-consumer
          image: producer:latest
          imagePullPolicy: Never
          command: ["php", "bin/console", "messenger:consume", "confirmation", "-vv"]
          envFrom:
            - configMapRef:
                name: producer-config
          volumeMounts:
            - name: log-volume
              mountPath: /app/var/log
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

      volumes:
        - name: log-volume
          emptyDir: {}
