apiVersion: v1
kind: Service
metadata:
  name: rabbit2
  namespace: distributed-rabbit
spec:
  selector:
    app: rabbit2
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
  type: ClusterIP
