apiVersion: batch/v1
kind: Job
metadata:
  name: rabbit-setup
  namespace: distributed-rabbit
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: curlimages/curl:latest
          command: ["/bin/sh", "/setup/run.sh"]
          volumeMounts:
            - name: setup-script
              mountPath: /setup
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: setup-script
          configMap:
            name: rabbitmq-setup-script
            defaultMode: 0755
